# Generated by Django 4.2.7 on 2025-07-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('fiber_per_100g', models.FloatField(blank=True, null=True)),
                ('sugar_per_100g', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
